apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cowk8s
  namespace: mail
spec:
  isCA: true
  commonName: cowk8s
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io